rem a var and const to play with
var x = 0
const y = 0

var y = 1

func badLocalFunc() local
    x = 1
end

func localFunc(int ref arg) local
    arg = 1
end

func globalFunc() global
    x = 2
end

func localFunc2() local
    var y = 1
end

func globalFunc2() global
    var y = 1
end

rem good. pass the variable in as a ref and it will work. 
localFunc(x)
print x

rem global functions can modify script level variables
globalFunc()
print x

rem localFunc2()
print y

globalFunc2()
print y

rem local function attempts to set a global variable. Will error out if uncommented
rem badLocalFunc()
